# Production Configuration for Photostudio ComfyUI
# Environment: Production
# Use: High-throughput, enterprise-grade ghost mannequin generation

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8188
  workers: 4
  timeout: 600
  max_queue_size: 50

# Resource Management
resources:
  # GPU Configuration
  gpu:
    memory_management: "auto"  # auto, lowvram, novram
    device_id: 0
    max_vram_gb: 24
    offload_models: true
    
  # CPU Configuration  
  cpu:
    max_workers: 8
    thread_limit: 16
    memory_limit_gb: 32
    
  # Storage
  storage:
    input_dir: "/app/input"
    output_dir: "/app/output"
    models_dir: "/app/models"
    temp_dir: "/app/temp"
    cleanup_interval_hours: 24
    max_storage_gb: 500

# Workflow Configuration
workflow:
  default_workflow: "ghostmannequin_comfyui_v1.json"
  
  # Generation Settings
  generation:
    default_steps: 25
    default_cfg: 8.0
    default_sampler: "euler_ancestral"
    default_scheduler: "normal"
    seed_mode: "random"  # random, fixed, increment
    
  # Quality Settings
  quality:
    min_resolution: [1024, 1024]
    max_resolution: [2048, 2048]
    output_format: "PNG"
    jpeg_quality: 95
    png_compression: 6

# Batch Processing
batch:
  max_concurrent_workflows: 4
  retry_failed_items: true
  max_retries: 2
  progress_update_interval: 10
  
  # Reporting
  reporting:
    generate_csv: true
    generate_summary: true
    save_config_snapshot: true
    metrics_enabled: true

# Monitoring & Logging
monitoring:
  # Logging Configuration
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    file_path: "/app/logs/comfyui.log"
    max_file_size_mb: 100
    backup_count: 10
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
  # Metrics
  metrics:
    enabled: true
    endpoint: "/metrics"
    collection_interval: 30
    retention_days: 30
    
  # Health Checks
  health_checks:
    enabled: true
    interval_seconds: 60
    endpoints:
      - "/health"
      - "/queue"
      - "/models"

# Security
security:
  # API Security
  api:
    enable_cors: false
    allowed_origins: []
    rate_limiting:
      enabled: true
      requests_per_minute: 120
      burst_size: 20
      
  # File Security
  file_security:
    max_file_size_mb: 100
    allowed_extensions: [".jpg", ".jpeg", ".png", ".webp"]
    scan_uploads: true
    
  # Network Security
  network:
    bind_localhost_only: false
    enable_https: true
    ssl_cert_path: "/app/certs/cert.pem"
    ssl_key_path: "/app/certs/key.pem"

# Model Configuration
models:
  # Required Models
  required:
    checkpoint: "sd_xl_base_1.0.safetensors"
    controlnet: "control_v11p_sd15_canny.pth"
    
  # Optional Models
  optional:
    vae: "sdxl_vae.safetensors"
    
  # Auto-download
  auto_download:
    enabled: true
    verify_integrity: true
    cleanup_temp_files: true
    retry_failed_downloads: true

# Integration Settings
integration:
  # External APIs
  apis:
    huggingface_token: "${HF_TOKEN}"
    webhook_url: "${WEBHOOK_URL}"
    
  # Database (if enabled)
  database:
    enabled: false
    connection_string: "${DATABASE_URL}"
    pool_size: 10
    timeout: 30
    
  # Message Queue (if enabled)  
  message_queue:
    enabled: false
    broker_url: "${REDIS_URL}"
    result_backend: "${REDIS_URL}"
    task_timeout: 3600

# Performance Tuning
performance:
  # Memory Optimization
  memory:
    aggressive_offloading: true
    model_caching: true
    clear_cache_interval: 300
    gc_threshold: 0.8
    
  # I/O Optimization
  io:
    async_file_operations: true
    buffer_size_mb: 64
    concurrent_uploads: 4
    concurrent_downloads: 2
    
  # Processing Optimization
  processing:
    parallel_preprocessing: true
    batch_size_optimization: true
    pipeline_caching: true
    fast_preview: false

# Backup & Recovery
backup:
  # Configuration Backup
  config_backup:
    enabled: true
    interval_hours: 24
    retention_days: 30
    location: "/app/backups/config"
    
  # Model Backup
  model_backup:
    enabled: false
    location: "/app/backups/models"
    compression: true
    
  # Output Backup
  output_backup:
    enabled: true
    interval_hours: 6
    retention_days: 7
    location: "/app/backups/output"
    sync_to_s3: false
    s3_bucket: "${S3_BACKUP_BUCKET}"

# Development & Debug (disabled in production)
debug:
  enabled: false
  detailed_errors: false
  profiling: false
  save_intermediate_results: false
  webhook_debug: false